name: Build Windows Binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows 10
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Cargo and target dir
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build in release mode
        run: cargo build --release

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-binary
          path: target/release/*.exe
